can_baudrate: 500
module_ids: [1,2,3,4,5,6,7]
arm_name: left_arm
arm_select: left
joint_names: [left_arm_1_joint, left_arm_2_joint, left_arm_3_joint, left_arm_4_joint, left_arm_5_joint, left_arm_6_joint, left_arm_7_joint]
max_accelerations: [1.658, 1.658, 1.658, 1.658, 1.745, 1.745, 1.745]
frequency: 150
min_publish_duration: 0.1
OperationMode: position
serial_number_module1: 41261
horizon: 0.1

# trajectory controller parameters
ptp_vel: 0.4 # rad/sec
ptp_acc: 0.2 # rad/sec^2
max_error: 0.1 # rad

gripper: PG70 
