
# this calibration is with the robotiq hand!!!

loop_frequency: 650
read_frequency: 650
serial_number: FT9909
arm_select: right
bias: [4.3293,  -15.1797,   -6.2509,   -0.6456,    0.3949, -0.2448]

end_effector_mass: 2.77349

# coefficients 2nd order butterworth LPF (2 Hz cutoff frequency)
b: [0.0002414, 0.0004827, 0.0002414]
a: [1.0000,   -1.9556,    0.9565]